[env:heltec_wireless_stick_lite_v3]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino

monitor_speed = 115200
upload_speed = 921600

lib_deps =
  jgromes/RadioLib@^7.7.0
  mikalhart/TinyGPSPlus@^1.1.0

build_flags =
  -DCORE_DEBUG_LEVEL=0
  -Iinclude
