#pragma once

enum FT02PageState
{
    FT02_PAGE_HOME = 0,
    FT02_PAGE_HELP,
    FT02_PAGE_MAP,
    FT02_PAGE_KNOWLEDGE,
    FT02_PAGE_LOCATION_RECORDER,
    FT02_PAGE_LOCATION_LOG_LIST,
    FT02_PAGE_LOCATION_LOG_DETAIL,
    FT02_PAGE_LOCATION_LOG_DELETE_CONFIRM,
    FT02_PAGE_AUDIO_LOG_LIST,
    FT02_PAGE_AUDIO_LOG_DELETE_CONFIRM,
    FT02_PAGE_COMMUNICATION
};
